import = [
  "/home/nguyen/.nvm/versions/node/v20.13.1/lib/node_modules/alacritty-themes/themes/Greenscreen.dark.toml"
]

[window]
position = "None"
dynamic_padding = false
decorations = "Full"
opacity = 0.95
blur = false
startup_mode = "FullScreen"
title = "Alacritty"
dynamic_title = true
decorations_theme_variant = "None"
resize_increments = false
option_as_alt = "None"

  [window.dimensions]
  columns = 0
  lines = 0

  [window.padding]
  x = 0
  y = 0

  [window.class]
  instance = "Alacritty"
  general = "Alacritty"

[scrolling]
history = 10_000
multiplier = 3

[font]
size = 11.25
builtin_box_drawing = true

  [font.normal]
  family = "Monaspace Xenon Var"
  style = "Medium"

  [font.bold]
  style = "Bold"

  [font.italic]
  style = "Italic"

  [font.bold_italic]
  style = "Bold Italic"

  [font.offset]
  x = 0
  y = 0

  [font.glyph_offset]
  x = 0
  y = 0

[colors]
transparent_background_colors = true
draw_bold_text_with_bright_colors = true

  [colors.primary]
  foreground = "#d8d8d8"
  background = "#181818"
  dim_foreground = "#828482"
  bright_foreground = "None"

  [colors.cursor]
  text = "CellBackground"
  cursor = "CellForeground"

  [colors.vi_mode_cursor]
  text = "CellBackground"
  cursor = "CellForeground"

[colors.search.matches]
foreground = "#181818"
background = "#ac4242"

[colors.search.focused_match]
foreground = "#181818"
background = "#f4bf75"
#
[colors.hints.start]
foreground = "#181818"
background = "#f4bf75"

[colors.hints.end]
foreground = "#181818"
background = "#ac4242"

  [colors.line_indicator]
  foreground = "None"
  background = "None"

  [colors.footer_bar]
  foreground = "#181818"
  background = "#d8d8d8"

  [colors.selection]
  text = "CellBackground"
  background = "CellForeground"

  [colors.normal]
  black = "#181818"
  red = "#ac4242"
  green = "#90a959"
  yellow = "#f4bf75"
  blue = "#6a9fb5"
  magenta = "#aa759f"
  cyan = "#75b5aa"
  white = "#d8d8d8"

  [colors.bright]
  black = "#6b6b6b"
  red = "#c55555"
  green = "#aac474"
  yellow = "#feca88"
  blue = "#7AC74F"
  magenta = "#c28cb8"
  cyan = "#93d3c3"
  white = "#f8f8f8"

  [colors.dim]
  black = "#0f0f0f"
  red = "#712b2b"
  green = "#5f6f3a"
  yellow = "#a17e4d"
  blue = "#456877"
  magenta = "#704d68"
  cyan = "#4d7770"
  white = "#8e8e8e"

[bell]
animation = "Linear"
duration = 0
color = "#ffffff"
command = "None"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\\t"
save_to_clipboard = false

[cursor]
vi_mode_style = "None"
blink_interval = 750
blink_timeout = 0
unfocused_hollow = true
thickness = 0.15

  [cursor.style]
  shape = "Block"
  blinking = "On"

[terminal]
osc52 = "CopyPaste"

[mouse]
hide_when_typing = true
bindings = [ ]

[hints]
alphabet = "jfkdls;ahgurieowpq"

[keyboard]
bindings = [ ]
